FROM node:24.1.0

# Install pnpm
RUN npm install -g pnpm@10.11.1

WORKDIR /app

# Copy workspace files
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./

# Copy all packages and apps
COPY packages ./packages/
COPY apps ./apps/

# Install dependencies
RUN pnpm install --frozen-lockfile

# Build shared package first
RUN pnpm run build:shared

# Build API
RUN pnpm run build:api

# Set working directory to API
WORKDIR /app/apps/api

EXPOSE 3000

CMD ["pnpm", "start"]