// Petfinder-approved colors (must match exactly as specified in Petfinder documentation)
export const DOG_COLORS = [
  'Black',
  'Black / Tan',
  'Black / White',
  'Blue / Gray',
  'Brindle',
  'Brown / Chocolate',
  'Cream',
  'Fawn',
  'Golden',
  'Gray',
  'Merle',
  'Red / Chestnut / Orange',
  'Sable',
  'Silver',
  'Tan / Yellow / Fawn',
  'Tricolor (Brown, Black, & White)',
  'White',
  'White / Black',
  'White / Brown',
  'White / Cream',
  'White / Golden',
  'White / Gray',
  'White / Red',
  'White / Tan',
  'Yellow',
];

// Petfinder-approved coat lengths (must match exactly as specified in Petfinder documentation)
export const COAT_LENGTHS = [
  'Hairless',
  'Short',
  'Medium',
  'Long',
  'Wire',
  'Curly',
];

// Petfinder-approved age categories (must match exactly as specified in Petfinder documentation)
export const AGE_CATEGORIES = [
  'Baby',
  'Young', 
  'Adult',
  'Senior',
];

export const DOG_BREEDS = [
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akbash',
  'Akita',
  'Alaskan Malamute',
  'American Bulldog',
  'American Eskimo Dog',
  'American Hairless Terrier',
  'American Staffordshire Terrier',
  'American Water Spaniel',
  'Anatolian Shepherd',
  'Appenzell Mountain Dog',
  'Australian Cattle Dog / Blue Heeler',
  'Australian Kelpie',
  'Australian Shepherd',
  'Australian Terrier',
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Bearded Collie',
  'Beauceron',
  'Bedlington Terrier',
  'Belgian Shepherd / Sheepdog',
  'Belgian Shepherd / Laekenois',
  'Belgian Shepherd / Malinois',
  'Belgian Shepherd / Tervuren',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Black and Tan Coonhound',
  'Black Labrador Retriever',
  'Black Mouth Cur',
  'Black Russian Terrier',
  'Bloodhound',
  'Blue Lacy',
  'Bluetick Coonhound',
  'Boerboel',
  'Bolognese',
  'Border Collie',
  'Border Terrier',
  'Borzoi',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxer',
  'Boykin Spaniel',
  'Briard',
  'Brittany Spaniel',
  'Brussels Griffon',
  'Bull Terrier',
  'Bullmastiff',
  'Cairn Terrier',
  'Canaan Dog',
  'Cane Corso',
  'Carolina Dog',
  'Catahoula Leopard Dog',
  'Cattle Dog',
  'Caucasian Sheepdog / Caucasian Ovtcharka',
  'Cavalier King Charles Spaniel',
  'Chesapeake Bay Retriever',
  'Chihuahua',
  'Chinese Crested Dog',
  'Chinese Foo Dog',
  'Chinook',
  'Chocolate Labrador Retriever',
  'Chow Chow',
  "Cirneco dell'Etna",
  'Clumber Spaniel',
  'Cockapoo',
  'Cocker Spaniel',
  'Collie',
  'Coonhound',
  'Corgi',
  'Coton de Tulear',
  'Curly-Coated Retriever',
  'Dachshund',
  'Dalmatian',
  'Dandie Dinmont Terrier',
  'Doberman Pinscher',
  'Dogo Argentino',
  'Dogue de Bordeaux',
  'Dutch Shepherd',
  'English Bulldog',
  'English Cocker Spaniel',
  'English Coonhound',
  'English Pointer',
  'English Setter',
  'English Shepherd',
  'English Springer Spaniel',
  'English Toy Spaniel',
  'Entlebucher',
  'Eskimo Dog',
  'Feist',
  'Field Spaniel',
  'Fila Brasileiro',
  'Finnish Lapphund',
  'Finnish Spitz',
  'Flat-Coated Retriever',
  'Fox Terrier',
  'Foxhound',
  'French Bulldog',
  'Galgo Spanish Greyhound',
  'German Pinscher',
  'German Shepherd Dog',
  'German Shorthaired Pointer',
  'German Spitz',
  'German Wirehaired Pointer',
  'Giant Schnauzer',
  'Glen of Imaal Terrier',
  'Golden Retriever',
  'Gordon Setter',
  'Great Dane',
  'Great Pyrenees',
  'Greater Swiss Mountain Dog',
  'Greyhound',
  'Harrier',
  'Havanese',
  'Hound',
  'Hovawart',
  'Husky',
  'Ibizan Hound',
  'Illyrian Sheepdog',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Italian Greyhound',
  'Spinone Italiano',
  'Jack Russell Terrier',
  'Parson Russell Terrier',
  'Japanese Chin',
  'Jindo',
  'Kai Dog',
  'Karelian Bear Dog',
  'Keeshond',
  'Kerry Blue Terrier',
  'Kishu',
  'Klee Kai',
  'Komondor',
  'Kuvasz',
  'Kyi Leo',
  'Labrador Retriever',
  'Lakeland Terrier',
  'Lancashire Heeler',
  'Leonberger',
  'Lhasa Apso',
  'Lowchen',
  'Maltese',
  'Manchester Terrier',
  'Maremma Sheepdog',
  'Mastiff',
  'McNab',
  'Miniature Pinscher',
  'Mountain Cur',
  'Mountain Dog',
  'Munsterlander',
  'Neapolitan Mastiff',
  'New Guinea Singing Dog',
  'Newfoundland Dog',
  'Norfolk Terrier',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Old English Sheepdog',
  'Otterhound',
  'Papillon',
  'Patterdale Terrier / Fell Terrier',
  'Pekingese',
  'Peruvian Inca Orchid',
  'Petit Basset Griffon Vendeen',
  'Pharaoh Hound',
  'Pit Bull Terrier',
  'Plott Hound',
  'Portuguese Podengo',
  'Pointer',
  'Polish Lowland Sheepdog',
  'Pomeranian',
  'Poodle',
  'Portuguese Water Dog',
  'Presa Canario',
  'Pug',
  'Puli',
  'Pumi',
  'Rat Terrier',
  'Redbone Coonhound',
  'Retriever',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Saint Bernard',
  'Saluki',
  'Samoyed',
  'Sarplaninac',
  'Schipperke',
  'Schnauzer',
  'Scottish Deerhound',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Shar-Pei',
  'Sheep Dog',
  'Shepherd',
  'Shetland Sheepdog / Sheltie',
  'Shiba Inu',
  'Shih Tzu',
  'Siberian Husky',
  'Silky Terrier',
  'Skye Terrier',
  'Sloughi',
  'Smooth Fox Terrier',
  'South Russian Ovtcharka',
  'Spaniel',
  'Spitz',
  'Staffordshire Bull Terrier',
  'Standard Poodle',
  'Sussex Spaniel',
  'Swedish Vallhund',
  'Terrier',
  'Thai Ridgeback',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Tosa Inu',
  'Toy Fox Terrier',
  'Treeing Walker Coonhound',
  'Vizsla',
  'Weimaraner',
  'Cardigan Welsh Corgi',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'West Highland White Terrier / Westie',
  'Wheaten Terrier',
  'Whippet',
  'White German Shepherd',
  'Wire Fox Terrier',
  'Wirehaired Pointing Griffon',
  'Wirehaired Terrier',
  'Xoloitzcuintli / Mexican Hairless',
  'Yellow Labrador Retriever',
  'Yorkshire Terrier',
  'Setter',
  'Icelandic Sheepdog',
  'Hamiltonstovare',
  'Miniature Schnauzer',
  'Mixed Breed',
  'Rough Collie',
  'Smooth Collie',
  'Spanish Water Dog',
  'Standard Schnauzer',
  'Wirehaired Dachshund',
  'American Foxhound',
  'Miniature Bull Terrier',
  'Miniature Dachshund',
  'English Foxhound',
  'Toy Manchester Terrier',
  'Pembroke Welsh Corgi',
  'Miniature Poodle',
  'Pyrenean Shepherd',
];

